spring:
  application:
    name: payment-service

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info

# spring:
#   data:
#     mongodb:
#       uri: ${MONGODB_URI:mongodb://localhost:27017/nhom611}
#   kafka:
#     bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
